name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to github repo(package)
      run: |
        echo $CR_PAT | docker login ghcr.io -u Kritika786 --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
    - name: Build the Docker image
      run: |
         docker build ./frontend/ --tag my-image-name:$(date +%s)
         docker run ghcr.io/kritika786/docker-nginx/fronted:my-image-name:$(date +%s)
         docker push ghcr.io/kritika786/docker-nginx/fronted:my-image-name:$(date +%s)
           
